import { useState } from 'react'
import { adminApi } from '@/api/endpoints'
import type { ProductPriceTier } from '@/types/api'
const L={t:'\uac00\uaca9\ub300 \uc548\ub0b4 \ube0c\ub79c\ub4dc \uad00\ub9ac',i:'\uc0c1\ud488 ID',q:'\uc870\ud68c',a:'\uac00\uaca9\ub300 \ucd94\uac00',e:'\uc218\uc815',d:'\ube44\ud65c\uc131\ud654'}
export function PriceTierManagementPanel(){
const [id,setId]=useState('');const [items,setItems]=useState<ProductPriceTier[]>([]);const [error,setError]=useState('')
const load=async()=>{if(!id)return;try{setItems(await adminApi.priceTiers(Number(id)));setError('')}catch{setError('가격대 조회에 실패했습니다.')}}
const add=async()=>{const label=prompt('\uac00\uaca9\ub300\uba85');const salePrice=Number(prompt('\uac00\uaca9'));const guideBrands=prompt('\uc548\ub0b4 \ube0c\ub79c\ub4dc');const guideMessage=prompt('\uacf5\uc9c0 \ubb38\uad6c');if(label&&guideBrands&&guideMessage){await adminApi.createPriceTier(Number(id),{label,salePrice,guideBrands,guideMessage,sortOrder:items.length});await load()}}
const edit=async(t:ProductPriceTier)=>{const label=prompt('\uac00\uaca9\ub300\uba85',t.label)??t.label;const salePrice=Number(prompt('\uac00\uaca9',String(t.salePrice))??t.salePrice);const guideBrands=prompt('\uc548\ub0b4 \ube0c\ub79c\ub4dc',t.guideBrands)??t.guideBrands;const guideMessage=prompt('\uacf5\uc9c0 \ubb38\uad6c',t.guideMessage)??t.guideMessage;await adminApi.updatePriceTier(t.id,{label,salePrice,guideBrands,guideMessage,sortOrder:t.sortOrder??0});await load()}
return <section className="rounded-2xl border border-brand-100 bg-white p-5 shadow-sm"><p className="text-xs font-black text-brand-600">PRICE TIER POLICY</p><h2 className="mt-1 text-lg font-black text-slate-900">{L.t}</h2>
<div className="mt-3 flex gap-2"><input value={id} onChange={e=>setId(e.target.value)} placeholder={L.i} className="rounded-xl border px-3 py-2 text-sm"/><button type="button" onClick={()=>void load()} className="rounded-xl bg-slate-900 px-3 py-2 text-sm font-bold text-white">{L.q}</button><button type="button" onClick={()=>void add()} className="rounded-xl bg-brand-600 px-3 py-2 text-sm font-bold text-white">{L.a}</button></div>
{error?<p className="mt-3 text-sm text-rose-600">{error}</p>:null}<div className="mt-4 space-y-2">{items.map(t=><div key={t.id} className="flex items-center justify-between gap-2 rounded-xl border p-3 text-sm"><span><b>{t.label}  {t.salePrice.toLocaleString()}원</b><span className="ml-2 text-slate-500">{t.guideBrands}</span></span><span className="flex gap-3"><button type="button" onClick={()=>void edit(t)} className="font-bold text-brand-700">{L.e}</button><button type="button" onClick={()=>void adminApi.removePriceTier(t.id).then(load)} className="font-bold text-rose-600">{L.d}</button></span></div>)}</div></section>
}
