import { useEffect, useState } from 'react'
import { sellerSubscriptionApi } from '../../api/endpoints'
import type { SellerSubscriptionStatus, SubscriptionProduct } from '../../types/api'

const LABEL: Record<string, string> = { PREMIUM: '프리미엄', GOLD: '골드', SILVER: '실버', PURCHASED: '결제 자동 승인', ADMIN_CHANGED: '관리자 등급 조절', EXPIRED: '구독 기간 만료' }
const won = (value: number) => new Intl.NumberFormat('ko-KR').format(value) + '원'
const dateTime = (value: string | null) => value ? new Date(value).toLocaleString('ko-KR') : '-'

export default function SellerSubscriptionPage() {
  const [status, setStatus] = useState<SellerSubscriptionStatus | null>(null)
  const [products, setProducts] = useState<SubscriptionProduct[]>([])
  const [error, setError] = useState('')
  const [busy, setBusy] = useState<number | null>(null)
  const load = async () => { try { const [nextStatus, nextProducts] = await Promise.all([sellerSubscriptionApi.status(), sellerSubscriptionApi.products()]); setStatus(nextStatus); setProducts(nextProducts); setError('') } catch (err) { setError(err instanceof Error ? err.message : '구독 정보를 불러오지 못했습니다.') } }
  useEffect(() => { void load() }, [])
  const purchase = async (product: SubscriptionProduct) => { setBusy(product.id); try { setStatus(await sellerSubscriptionApi.purchase(product.id)); window.alert(product.name + ' 구독이 자동 승인되었습니다.'); } catch (err) { setError(err instanceof Error ? err.message : '구독 처리에 실패했습니다.') } finally { setBusy(null) } }
  return <div className="page stack"><section className="card p-5"><p className="text-xs font-black text-violet-700">SELLER MEMBERSHIP</p><h1 className="mt-1 text-2xl font-black">판매자 구독</h1><p className="mt-2 text-sm text-slate-600">구독 결제는 개발 단계에서 자동 승인됩니다. 등급별 주문 공개 시간과 가용 슬롯을 확인하세요.</p>{status && <div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-violet-50 p-4"><p className="text-xs font-bold text-violet-700">현재 등급</p><p className="mt-1 text-xl font-black">{LABEL[status.tier]}</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs font-bold text-slate-600">구독 만료</p><p className="mt-1 text-sm font-black">{dateTime(status.subscriptionExpiresAt)}</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs font-bold text-slate-600">주문 공개</p><p className="mt-1 text-sm font-black">{status.tier === 'PREMIUM' ? '즉시 · 30초 독점' : status.tier === 'GOLD' ? '주문 후 30초' : '주문 후 60초'}</p></div></div>}</section>{error && <p className="rounded-xl bg-red-50 p-4 text-sm font-bold text-red-700">{error}</p>}<section className="card p-5"><h2 className="text-lg font-black">구독 상품</h2>{products.length === 0 ? <p className="mt-4 text-sm text-slate-500">현재 판매 중인 구독 상품이 없습니다. 관리자에게 상품 등록을 요청하세요.</p> : <div className="mt-4 grid gap-4 md:grid-cols-2">{products.map(product => <article key={product.id} className="rounded-2xl border border-slate-200 p-5"><p className="text-xs font-black text-violet-700">{LABEL[product.tier]}</p><h3 className="mt-1 text-lg font-black">{product.name}</h3><p className="mt-2 text-sm text-slate-600">{product.description || '멤버십 우선 응찰과 가용 슬롯 혜택을 제공합니다.'}</p><p className="mt-4 text-xl font-black">{won(product.price)} <span className="text-sm text-slate-500">/ {product.durationMonths}개월</span></p><button type="button" disabled={busy === product.id} onClick={() => void purchase(product)} className="mt-4 w-full rounded-xl bg-violet-600 px-4 py-3 text-sm font-black text-white disabled:opacity-50">{busy === product.id ? '처리 중' : '구독 결제·자동 승인'}</button></article>)}</div>}</section><section className="card p-5"><h2 className="text-lg font-black">등급 변경 히스토리</h2>{(status?.history.length ?? 0) === 0 ? <p className="mt-4 text-sm text-slate-500">아직 구독 변경 이력이 없습니다.</p> : <div className="mt-4 overflow-x-auto"><table className="table"><thead><tr><th>시각</th><th>변경</th><th>처리</th><th>만료일</th><th>사유</th></tr></thead><tbody>{status?.history.map(item => <tr key={item.id}><td>{dateTime(item.createdAt)}</td><td>{LABEL[item.previousTier]} → {LABEL[item.nextTier]}</td><td>{LABEL[item.eventType]}</td><td>{dateTime(item.expiresAt)}</td><td>{item.reason || '-'}</td></tr>)}</tbody></table></div>}</section></div>
}

