create table refunds (
    id bigint generated by default as identity primary key,
    payment_id bigint not null references payments(id),
    order_id bigint not null references orders(id),
    refund_type varchar(20) not null,
    amount integer not null check (amount > 0),
    reason varchar(500) not null,
    idempotency_key varchar(100) not null unique,
    status varchar(20) not null,
    requested_by_user_id bigint not null references users(id),
    processed_by_user_id bigint references users(id),
    pg_cancel_key varchar(120),
    pg_response_message varchar(500),
    created_at timestamptz not null,
    completed_at timestamptz,
    version bigint,
    constraint ck_refunds_type check (refund_type in ('CANCEL', 'REFUND')),
    constraint ck_refunds_status check (status in ('REQUESTED', 'SUCCEEDED', 'FAILED'))
);

create index ix_refunds_payment_created on refunds(payment_id, created_at desc);
