create table settlements (
    id bigint generated by default as identity primary key,
    order_id bigint not null unique references orders(id),
    store_id bigint not null references stores(id),
    payment_id bigint references payments(id),
    gross_amount integer not null check (gross_amount >= 0),
    status varchar(20) not null,
    hold_reason varchar(500),
    held_at timestamptz,
    released_at timestamptz,
    created_at timestamptz not null,
    updated_at timestamptz not null,
    version bigint,
    constraint ck_settlement_status check (status in ('PENDING', 'HOLD', 'RELEASABLE', 'SETTLED', 'CANCELLED'))
);

create table claims (
    id bigint generated by default as identity primary key,
    order_id bigint not null references orders(id),
    consumer_id bigint not null references users(id),
    store_id bigint not null references stores(id),
    claim_type varchar(30) not null,
    reason_code varchar(50) not null,
    description varchar(2000) not null,
    status varchar(30) not null,
    created_at timestamptz not null,
    updated_at timestamptz not null,
    resolved_at timestamptz,
    version bigint,
    constraint ck_claim_type check (claim_type in ('RETURN', 'EXCHANGE', 'PARTIAL_REPLACEMENT')),
    constraint ck_claim_status check (status in ('REQUESTED', 'SELLER_REVIEWING', 'PICKUP_SCHEDULED', 'REPLACEMENT_SHIPPING', 'ESCALATED', 'RESOLVED', 'REJECTED'))
);
create unique index ux_claims_active_order on claims(order_id) where status not in ('RESOLVED', 'REJECTED');
create index ix_claims_store_status on claims(store_id, status, created_at desc);
create index ix_claims_consumer_created on claims(consumer_id, created_at desc);

create table claim_evidences (
    id bigint generated by default as identity primary key,
    claim_id bigint not null references claims(id) on delete cascade,
    object_key varchar(300) not null unique,
    content_type varchar(100) not null,
    byte_size bigint not null check (byte_size > 0),
    created_at timestamptz not null
);

create table claim_events (
    id bigint generated by default as identity primary key,
    claim_id bigint not null references claims(id) on delete cascade,
    event_type varchar(50) not null,
    actor_user_id bigint references users(id),
    actor_role varchar(30) not null,
    detail varchar(2000) not null,
    created_at timestamptz not null
);
create index ix_claim_events_claim_created on claim_events(claim_id, created_at);
