create table coupons (
    id bigint generated by default as identity primary key,
    code varchar(40) not null unique,
    title varchar(100) not null,
    discount_amount integer not null check (discount_amount > 0),
    minimum_order_amount integer not null check (minimum_order_amount >= 0),
    starts_at timestamptz not null,
    expires_at timestamptz not null,
    active boolean not null default true,
    created_by bigint references users(id),
    created_at timestamptz not null,
    constraint ck_coupon_period check (expires_at > starts_at)
);

create table coupon_issues (
    id bigint generated by default as identity primary key,
    coupon_id bigint not null references coupons(id),
    consumer_id bigint not null references users(id),
    status varchar(20) not null,
    applied_order_id bigint unique references orders(id),
    issued_at timestamptz not null,
    applied_at timestamptz,
    restored_at timestamptz,
    expires_at timestamptz not null,
    constraint ck_coupon_issue_status check (status in ('AVAILABLE', 'APPLIED', 'EXPIRED', 'CANCELLED'))
);
create index ix_coupon_issues_consumer_status on coupon_issues(consumer_id, status, expires_at);

create table coupon_events (
    id bigint generated by default as identity primary key,
    coupon_issue_id bigint not null references coupon_issues(id),
    event_type varchar(30) not null,
    actor_user_id bigint references users(id),
    detail varchar(500) not null,
    created_at timestamptz not null
);
create index ix_coupon_events_issue_created on coupon_events(coupon_issue_id, created_at);

alter table orders add column coupon_issue_id bigint unique references coupon_issues(id);
