create table product_price_tiers (
    id bigint generated by default as identity primary key,
    product_id bigint not null references products(id) on delete cascade,
    label varchar(80) not null,
    sale_price integer not null check (sale_price >= 0),
    guide_brands varchar(1000) not null,
    guide_message varchar(1000) not null,
    sort_order integer not null default 0,
    active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint ux_product_price_tiers_product_label unique(product_id, label)
);
create index ix_product_price_tiers_product_active on product_price_tiers(product_id, active, sort_order);

alter table cart_items add column price_tier_id bigint references product_price_tiers(id);
alter table cart_items add column price_tier_label varchar(80);
alter table cart_items add column price_tier_price integer;
alter table cart_items add column price_tier_brands varchar(1000);
alter table carts add column price_tier_agreed boolean not null default false;
alter table carts add column price_tier_agreed_at timestamptz;

alter table order_items add column price_tier_id bigint;
alter table order_items add column price_tier_label varchar(80);
alter table order_items add column price_tier_brands varchar(1000);
alter table order_items add column price_tier_agreed boolean not null default false;

insert into product_price_tiers(product_id, label, sale_price, guide_brands, guide_message, sort_order)
select id, 'Basic price tier', price, coalesce(nullif(brand, ''), 'Available store brands'), 'Items in this price tier may be supplied with the seller''s available brand. See the price-tier brand guide.', 0
from products;

update cart_items ci
set price_tier_id = tier.id, price_tier_label = tier.label, price_tier_price = tier.sale_price, price_tier_brands = tier.guide_brands
from product_price_tiers tier
where tier.product_id = ci.product_id and tier.sort_order = 0;

alter table cart_items alter column price_tier_id set not null;
alter table cart_items alter column price_tier_label set not null;
alter table cart_items alter column price_tier_price set not null;
alter table cart_items alter column price_tier_brands set not null;
