-- Chulsoo-ya PostgreSQL / Supabase baseline schema
-- 적용 대상: spring.profiles.active=supabase
-- 적용 전: 본 파일을 Supabase SQL Editor 또는 psql로 단 한 번 실행한다.
-- JPA의 ddl-auto=validate는 이 스키마가 애플리케이션 엔티티와 일치하는지만 검증한다.

create table users (
    id bigint generated by default as identity primary key,
    supabase_user_id uuid unique,
    email varchar(255) not null unique,
    name varchar(255) not null,
    phone varchar(255),
    role varchar(20) not null,
    created_at timestamptz not null default now(),
    constraint ck_users_role check (role in ('CONSUMER', 'SELLER', 'ADMIN'))
);

create table categories (
    id bigint generated by default as identity primary key,
    code varchar(50) not null unique,
    name varchar(100) not null,
    icon_key varchar(50),
    sort_order integer not null
);

create table products (
    id bigint generated by default as identity primary key,
    category_id bigint not null references categories(id),
    name varchar(200) not null,
    spec_summary varchar(300),
    price integer not null check (price >= 0),
    unit varchar(20),
    image_url varchar(500),
    active boolean not null default true
);
create index ix_products_category_active on products(category_id, active);
create index ix_products_name on products(name);

create table stores (
    id bigint generated by default as identity primary key,
    user_id bigint not null unique references users(id),
    name varchar(100) not null,
    gu_code varchar(20) not null,
    address varchar(300),
    phone varchar(255),
    tier varchar(20) not null default 'FREE',
    verified boolean not null default false,
    receiving_orders boolean not null default true,
    configured_slots integer not null default 3 check (configured_slots >= 0),
    reserved_slots integer not null default 0 check (reserved_slots >= 0),
    active_slots integer not null default 0 check (active_slots >= 0),
    restricted_until timestamptz,
    trust_score double precision not null default 60.0 check (trust_score >= 0 and trust_score <= 100),
    version bigint,
    constraint ck_stores_tier check (tier in ('PREMIUM', 'STANDARD', 'FREE')),
    constraint ck_stores_slot_balance check (configured_slots >= reserved_slots + active_slots)
);
create index ix_stores_eligible on stores(gu_code, verified, receiving_orders);

create table carts (
    id bigint generated by default as identity primary key,
    consumer_id bigint not null references users(id),
    active boolean not null default true,
    created_at timestamptz not null default now()
);
create unique index ux_carts_one_active_per_consumer on carts(consumer_id) where active = true;

create table cart_items (
    id bigint generated by default as identity primary key,
    cart_id bigint not null references carts(id) on delete cascade,
    product_id bigint not null references products(id),
    option_hash varchar(64) not null default '-',
    quantity integer not null check (quantity >= 1)
);
create unique index ux_cart_items_unique_product_option on cart_items(cart_id, product_id, option_hash);

create table orders (
    id bigint generated by default as identity primary key,
    consumer_id bigint not null references users(id),
    gu_code varchar(20) not null,
    status varchar(30) not null default 'DRAFT',
    fulfillment_method varchar(20) not null,
    address varchar(300),
    address_detail varchar(100),
    request_memo varchar(200),
    items_amount integer not null default 0 check (items_amount >= 0),
    delivery_fee integer not null default 0 check (delivery_fee >= 0),
    discount_amount integer not null default 0 check (discount_amount >= 0),
    winning_store_id bigint references stores(id),
    match_deadline_at timestamptz,
    seller_confirmation_deadline_at timestamptz,
    matched_at timestamptz,
    seller_confirmed_at timestamptz,
    paid_at timestamptz,
    delivery_started_at timestamptz,
    completed_at timestamptz,
    retry_count integer not null default 0 check (retry_count >= 0),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    version bigint,
    constraint ck_orders_status check (status in (
        'DRAFT', 'WAITING_MATCH', 'MATCHED', 'SELLER_CONFIRMING', 'PAYMENT_PENDING',
        'PAID', 'PREPARING', 'DELIVERY_IN_PROGRESS', 'PICKUP_READY', 'COMPLETED',
        'MATCH_FAILED', 'RE_MATCHING', 'CANCELLED'
    )),
    constraint ck_orders_fulfillment check (fulfillment_method in ('DELIVERY', 'PICKUP')),
    constraint ck_orders_discount_lte_items check (discount_amount <= items_amount)
);
create index ix_orders_consumer_created on orders(consumer_id, created_at desc);
create index ix_orders_winning_store on orders(winning_store_id, id desc);
create index ix_orders_matching_deadline on orders(status, match_deadline_at) where status = 'WAITING_MATCH';
create index ix_orders_confirm_deadline on orders(status, seller_confirmation_deadline_at) where status = 'SELLER_CONFIRMING';

create table order_items (
    id bigint generated by default as identity primary key,
    order_id bigint not null references orders(id) on delete cascade,
    product_id bigint not null references products(id),
    product_name varchar(200) not null,
    spec_summary varchar(300),
    unit varchar(20),
    quantity integer not null check (quantity >= 1),
    price_at_order integer not null check (price_at_order >= 0)
);
create index ix_order_items_order on order_items(order_id);

create table match_offers (
    id bigint generated by default as identity primary key,
    order_id bigint not null references orders(id),
    store_id bigint not null references stores(id),
    attempt integer not null check (attempt >= 0),
    tier varchar(20) not null,
    status varchar(20) not null default 'SENT',
    offered_at timestamptz not null,
    expires_at timestamptz not null,
    closed_at timestamptz,
    constraint ux_match_offers_one_per_attempt unique(order_id, store_id, attempt),
    constraint ck_match_offers_tier check (tier in ('PREMIUM', 'STANDARD', 'FREE')),
    constraint ck_match_offers_status check (status in ('SENT', 'DECLINED', 'EXPIRED', 'BID_SUBMITTED')),
    constraint ck_match_offers_expiry check (expires_at > offered_at)
);
create index ix_match_offers_store_open on match_offers(store_id, status, expires_at) where status = 'SENT';
create index ix_match_offers_expired on match_offers(status, expires_at) where status = 'SENT';

create table bids (
    id bigint generated by default as identity primary key,
    order_id bigint not null references orders(id),
    store_id bigint not null references stores(id),
    winner boolean not null default false,
    created_at timestamptz not null,
    confirmed_at timestamptz
);
create index ix_bids_order on bids(order_id);
create unique index ux_bids_one_winner_per_order on bids(order_id) where winner = true;

create table payments (
    id bigint generated by default as identity primary key,
    order_id bigint not null unique references orders(id),
    idempotency_key varchar(100) not null unique,
    amount integer not null check (amount >= 0),
    remaining_amount integer not null check (remaining_amount >= 0 and remaining_amount <= amount),
    status varchar(20) not null default 'READY',
    pg_transaction_key varchar(100),
    method varchar(30),
    created_at timestamptz not null default now(),
    paid_at timestamptz,
    constraint ck_payments_status check (status in (
        'READY', 'PAID', 'CANCEL_PENDING', 'CANCELLED', 'REFUNDING', 'PARTIAL_REFUNDED', 'REFUNDED'
    ))
);

create table store_slot_settings_logs (
    id bigint generated by default as identity primary key,
    store_id bigint not null references stores(id),
    old_configured_slots integer not null check (old_configured_slots >= 0),
    new_configured_slots integer not null check (new_configured_slots >= 0),
    changed_by varchar(20) not null,
    reason varchar(200),
    created_at timestamptz not null default now()
);
create index ix_slot_logs_store_created on store_slot_settings_logs(store_id, created_at desc);

create table missed_orders_logs (
    id bigint generated by default as identity primary key,
    store_id bigint not null references stores(id),
    order_id bigint not null references orders(id),
    reason varchar(30) not null,
    created_at timestamptz not null default now()
);
create index ix_missed_orders_store_created on missed_orders_logs(store_id, created_at desc);

