CREATE TABLE IF NOT EXISTS delivery_addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consumer_id BIGINT NOT NULL,
    label VARCHAR(30) NOT NULL,
    recipient_name VARCHAR(40) NOT NULL,
    recipient_phone VARCHAR(30) NOT NULL,
    city_name VARCHAR(30) NOT NULL,
    district_name VARCHAR(30) NOT NULL,
    road_address VARCHAR(180) NOT NULL,
    address_detail VARCHAR(180),
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_delivery_addresses_consumer_updated
    ON delivery_addresses(consumer_id, updated_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS uq_delivery_addresses_one_default_per_consumer
    ON delivery_addresses(consumer_id)
    WHERE is_default = TRUE;
