create table if not exists payment_methods (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users(id) on delete cascade,
    method_type varchar(20) not null,
    provider_name varchar(60) not null,
    last_four varchar(4) not null,
    created_at timestamptz not null default now(),
    constraint chk_payment_methods_type check (method_type in ('BANK_ACCOUNT', 'CARD')),
    constraint chk_payment_methods_last_four check (last_four ~ '^[0-9]{4}$')
);
create index if not exists idx_payment_methods_user_created on payment_methods(user_id, created_at desc);
