-- Premium/Gold/Silver seller subscription lifecycle.
alter table stores drop constraint if exists ck_stores_tier;
alter table stores add column if not exists subscription_expires_at timestamptz;
update stores set tier = 'GOLD' where tier = 'STANDARD';
update stores set tier = 'SILVER' where tier = 'FREE';
alter table stores alter column tier set default 'SILVER';
alter table stores add constraint ck_stores_tier check (tier in ('PREMIUM', 'GOLD', 'SILVER'));

alter table match_offers drop constraint if exists ck_match_offers_tier;
update match_offers set tier = 'GOLD' where tier = 'STANDARD';
update match_offers set tier = 'SILVER' where tier = 'FREE';
alter table match_offers add constraint ck_match_offers_tier check (tier in ('PREMIUM', 'GOLD', 'SILVER'));

create table if not exists subscription_products (
  id bigint generated by default as identity primary key,
  name varchar(100) not null,
  tier varchar(20) not null check (tier in ('PREMIUM', 'GOLD')),
  price integer not null check (price >= 0),
  duration_months integer not null default 1 check (duration_months between 1 and 12),
  description varchar(1000),
  active boolean not null default true,
  display_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists store_subscription_history (
  id bigint generated by default as identity primary key,
  store_id bigint not null references stores(id),
  product_id bigint references subscription_products(id),
  previous_tier varchar(20) not null,
  next_tier varchar(20) not null,
  previous_expires_at timestamptz,
  expires_at timestamptz,
  event_type varchar(30) not null check (event_type in ('PURCHASED', 'ADMIN_CHANGED', 'EXPIRED')),
  changed_by_user_id bigint references users(id),
  reason varchar(500),
  created_at timestamptz not null default now()
);
create index if not exists ix_store_subscription_history_store_time on store_subscription_history(store_id, created_at desc);
create index if not exists ix_stores_subscription_expiry on stores(subscription_expires_at) where subscription_expires_at is not null;
