alter table platform_maintenance_mode
    add column if not exists phase varchar(20) not null default 'NORMAL',
    add column if not exists planned_start_at timestamptz,
    add column if not exists planned_end_at timestamptz;

alter table platform_maintenance_mode
    add constraint platform_maintenance_mode_phase_check
    check (phase in ('NORMAL', 'PREPARING', 'MAINTENANCE'));

update platform_maintenance_mode
set phase = case when enabled then 'MAINTENANCE' else 'NORMAL' end
where phase is null or phase = 'NORMAL';

create table if not exists maintenance_notices (
    id bigint generated by default as identity primary key,
    title varchar(120) not null,
    content text not null,
    active boolean not null default false,
    popup_enabled boolean not null default true,
    display_start_at timestamptz,
    display_end_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    created_by_user_id bigint references users(id),
    updated_by_user_id bigint references users(id)
);

create index if not exists idx_maintenance_notices_active_window
    on maintenance_notices (active, display_start_at, display_end_at);
