-- Internal subscription payment workflow. PG approval can replace only the final approval trigger later.
create table if not exists subscription_payment_requests (
  id bigint generated by default as identity primary key,
  store_id bigint not null references stores(id),
  requester_user_id bigint not null references users(id),
  product_id bigint references subscription_products(id) on delete set null,
  product_name varchar(100) not null,
  tier varchar(20) not null check (tier in ('PREMIUM', 'GOLD')),
  amount integer not null check (amount >= 0),
  duration_months integer not null check (duration_months between 1 and 12),
  status varchar(20) not null check (status in ('PENDING', 'APPROVED', 'REJECTED')),
  requested_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by_user_id bigint references users(id),
  rejection_reason varchar(500)
);
create unique index if not exists uq_subscription_payment_requests_pending_store
  on subscription_payment_requests(store_id) where status = 'PENDING';
create index if not exists ix_subscription_payment_requests_status_time
  on subscription_payment_requests(status, requested_at asc);
create index if not exists ix_subscription_payment_requests_store_time
  on subscription_payment_requests(store_id, requested_at desc);
