create table penalties (
    id bigint generated by default as identity primary key,
    store_id bigint not null references stores(id),
    order_id bigint not null references orders(id),
    violation_type varchar(50) not null,
    level integer not null check (level >= 1),
    trust_score_delta double precision not null,
    restriction_until timestamptz,
    reason varchar(500) not null,
    applied_at timestamptz not null,
    constraint ck_penalties_violation_type check (violation_type in ('SELLER_CONFIRMATION_TIMEOUT')),
    constraint ux_penalties_order_violation unique (order_id, violation_type)
);

create index ix_penalties_store_applied on penalties(store_id, applied_at desc);
