create table dispatch_cursors (
    id bigint generated by default as identity primary key,
    gu_code varchar(20) not null,
    tier varchar(20) not null,
    next_position integer not null default 0,
    constraint ck_dispatch_cursors_tier check (tier in ('FREE', 'STANDARD', 'PREMIUM')),
    constraint ux_dispatch_cursors_region_tier unique (gu_code, tier)
);
